name: strspy_env 
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.7.7
# conda-forge channel installs
  - parallel
# bioconda channel installs
  - xatlas
  - samtools=1.12
  - bedtools
  - minimap2=2.18